### ISSUE TITLE
Nightly panic in cubeb caused by PA_SINK_SET_FORMATS flag (Firefox bug 1375873)

### ISSUE THREAD

**Issue by skierpage** [djg/cubeb-pulse-rs#11]
Hello, it appears this library is crashing some Linux users of Nightly Firefox, see https://bugzilla.mozilla.org/show_bug.cgi?id=1375873

There's a proposed patch to media/libcubeb/cubeb-pulse-rs/pulse-rs/src/lib.rs at https://reviewboard.mozilla.org/r/152352/diff/1#index_header

**Comment by djg** [comment]
Thanks for reporting. A fix was landed in https://bugzil.la/1376000, but the fix in https://bugzil.la/1375873 corrects the try_from function, so I've upstreamed it in PR #12.

**Comment by djg** [comment]
Fixed by #12
